name: 'AUR GitHub Updater'
description: 'Updates AUR packages that mirror releases from GitHub repositories'
author: 'KogasaPls'
inputs:
  pkgname:
    required: true
    description: 'The name of the AUR package'
outputs:
  pkgver:
    description: 'The new pkgver of the AUR package'

runs:
  using: 'node16'
  main: 'dist/index.js'
